import streamlit as st

st.title("Enterprise Financial AI Platform")

st.metric(

    "Portfolio Value",

    "$150 Million"

)

st.metric(

    "Portfolio VaR",

    "$2.3 Million"

)

question = st.text_input(

    "Ask Financial AI"

)

if question:

    st.success(

        "Response generated by AI"

    )